### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by CloneDeath**
Largest change is moving each relevant language into its own folder.
Created an ILanguageBackend interface to begin extracting what is really needed to add a new language.
Pulled in property for the file extension into the language backends, instead of a static function with switch/case statements. There are a few more static function that should be broken up and put into the backend and added to the interface, but this was just simply the easiest at first.
Removed Debug.Asserts from production code.
Fixed a few warnings, mostly values that are never used.
Cleaned up the code to match common C# conventions. Primarily just a few field/property renames.

### CODE REVIEW

**Comment by mellinoe** [comment]
Hey @CloneDeath, thanks for the submission and interest in the project. There's a few things that I wouldn't mind merging in here, but most of this I don't like and don't want -- namely the style changes.

* You've changed explicit types to `var` in a lot of places -- I don't want that. Obviously this one is just a personal preference, so there's not much to say.
* You've renamed a lot of fields, away from the `s_` prefix. I don't like this change, because the `s_` prefix has a conventional meaning (they are static fields). Removing the `s` implies that they are instance fields (they aren't), and making them capitalized and without a leading underscore implies they are public (they aren't). By the way, these are the conventions used by the projects in the .NET org.
* The ILanguageBackend interface adds no value. The abstract class already represents what is needed for a new language.
* The `Assert.Single` changes seem fine, but low value.
* Moving individual backends into their own namespaces seems okay -- it's something I've considered for a while but never bothered to do.
* I don't understand why you've removed the Debug assertions. These need to stay.
* I don't think the language backend should actually know what file extension it outputs. This is just a convention, so I'd rather the decision be made up in the command-line application, which is only one way to use ShaderGen.

Overall, there's a couple things in here that I might take, but most of it I wouldn't. Please file individual issues if you think something should be changed because I can't accept most of this as-is.

**Comment by CloneDeath** [comment]
* s_ Prefix
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions
This also aligns with most projects I see in C#. On static fields specifically, see the example in MessageQueue:
`public class MessageQueue {
    public static readonly TimeSpan InfiniteTimeout;
}
public struct UInt32 {
    public const Min = 0;
}`

* ILanguageBackend
Currently, LanguageBackend does a lot of things. It's not currently clear what needs to be implemented to add a new language. Furthermore, in order to implement a new language, one needs to currently touch many locations in the code (lots of type switches), which is really just a missed opportunity to use polymorphism.

* Assert.Single
Fix every warning.

* Debug.Assert
Added some back, in particular the ones that should be replaced with better unit tests. The problem with Debug assertions is that it alters the code flow between debug and release mode, and is really just a way of sneaking tests into production code.

* Extensions
This is the purpose of making them polymorphic. The extension is already abstract/virtual for each implementation, allowing anyone to override the output if desired.

**Comment by mellinoe** [comment]
> s_ Prefix
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions
This also aligns with most projects I see in C#. On static fields specifically, see the example in MessageQueue:

Those guidelines are obsolete, and furthermore don't actually offer any guidance for private fields at all. Take a look at some of the .NET repositories, you will see that they follow my style. I used to work on .NET and helped define some of the style rules that are actually in use.

Your example is a public field, which should be named differently from a non-public one.

> ILanguageBackend
Currently, LanguageBackend does a lot of things. It's not currently clear what needs to be implemented to add a new language. Furthermore, in order to implement a new language, one needs to currently touch many locations in the code (lots of type switches), which is really just a missed opportunity to use polymorphism.

I'm not disagreeing with this, the code is quite messy and spaghetti-like. But adding an extra interface does nothing to help -- in fact, it makes things worse because now there is another layer of abstraction for no gain.

> Debug.Assert
Added some back, in particular the ones that should be replaced with better unit tests. The problem with Debug assertions is that it alters the code flow between debug and release mode, and is really just a way of sneaking tests into production code.

This is another philosophical debate that I don't really want to get into. Suffice to say, though, removing the assertions with no extra tests is not good.

> This is the purpose of making them polymorphic. The extension is already abstract/virtual for each implementation, allowing anyone to override the output if desired.

I think it's the wrong layer to add the functionality, though. For example, I've considered adding functionality to ShaderGen.App to let you specify an output format for each backend. To me, that makes more sense because file extensions are kind of a subjective convention that people might disagree on.

**Comment by CloneDeath** [comment]
> I think it's the wrong layer to add the functionality, though. For example, I've considered adding functionality to ShaderGen.App to let you specify an output format for each backend. To me, that makes more sense because file extensions are kind of a subjective convention that people might disagree on.

I agree. I think that the binary compiled items should/could be another layer on top of the existing language backend. But first, the scattered implementations of code dependent on a specific LanguageBackend implementation makes it hard to know what is involved. This is just the first step of collecting that information.

Already, it looks like ILanguageBackend is really two interface: The file name extension property and the two code gen functions should be in their own interface, with a LanguageBackend specific implementation for each.

> Those guidelines are obsolete, and furthermore don't actually offer any guidance for private fields at all.
It's dated 2017

> Take a look at some of the .NET repositories, you will see that they follow my style.
Looking at 8 of the top trending C# repositories (skipping ports like TensorFlow, since they copy the patterns of the source language) for the past month:
https://github.com/shadowsocks/shadowsocks-windows/search?utf8=%E2%9C%93&q=%22private+static%22&type= (_camelCasing, with a couple exceptions)
https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=%22private+static%22&type= (Even mix of s_camelCasing, PascalCasing, and camelCasing)
https://github.com/dotnet-architecture/eShopOnContainers/search?utf8=%E2%9C%93&q=%22private+static%22&type= (even mix of PascalCasing and _camelCasing, with a few camelCasings mixed in)
https://github.com/0xd4d/dnSpy/search?utf8=%E2%9C%93&q=%22private+static%22&type= (s_camelCasing)
https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=%22private+static%22&type= (mixed, but mostly s_camelCasing)
https://github.com/Unity-Technologies/ShaderGraph/search?utf8=%E2%9C%93&q=%22private+static%22&type= (s_camelCasing)
https://github.com/ShareX/ShareX/search?utf8=%E2%9C%93&q=%22private+static%22&type= (mostly camelCasing or PasalCasing)
https://github.com/aspnetboilerplate/aspnetboilerplate/search?p=4&q=%22private+static%22&type=&utf8=%E2%9C%93 (Mostly PascalCasing with some _camelCasing)
https://github.com/NickeManarin/ScreenToGif/search?p=1&q=%22private+static%22&type=&utf8=%E2%9C%93 (Mix of _camelCasing, camelCasing, and PascalCasing)

camelCasing: 4
_camelCasing: 4
s_camelCasing: 4
PascalCasing: 5

Really it's a mixed bag. All things being equal, I'd like to quote Robert C. Martin's book Clean Code
> ## Member Prefixes
> You also don't need to prefix member variables with m_ anymore. Your classes and functions should be small enough that you don't need them. And you should be using and editing environment that highlights or colorizes members to make them distinct. <code example> Besides, people quickly learn to ignore the prefix (or suffix) to see the meaningful part of the name. The more we read the code, the less we see prefixes. Eventually the prefixes become unseen clutter and a marker of older code.

> Suffice to say, though, removing the assertions with no extra tests is not good.
I agree completely. I've added most of them back. The remaining that I've left out were redundant. An exception would be thrown immediately after anyways. If you disagree with any of the Debug.Asserts that are still gone, let me know.

**Comment by mellinoe** [comment]
I don't want to get into a style war really, so I'll just link to the guidelines I follow:

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

The only one I don't agree with is using `var`, but that's a "looser" rule anyways. Like I said, I helped define those rules. It's clear that there's no real consensus about what style to follow, but we thought through the rules in that document pretty thoroughly. By the way, the first two pages of the corefx are almost exclusively `s_`. The only exceptions are test code, which are just because nobody really cares about it enough.

> Already, it looks like ILanguageBackend is really two interface: The file name extension property and the two code gen functions should be in their own interface, with a LanguageBackend specific implementation for each.

I still disagree that `ILanguageBackend` should exist at all. Cleaning up the general abstraction is a noble goal, but adding interfaces just for the sake of it doesn't accomplish anything. Such a redesign would need to be thought through carefully and iterated on (and discussed).

At the moment, a LOT of stuff is just hacked together, because it was organically built as I learned the Roslyn API. It's pretty easy to identify stuff that is poorly-designed in here 😄. Luckily, there's a decent set of tests that should enable some refactoring.

**Comment by CloneDeath** [comment]
> I don't want to get into a style war really, so I'll just link to the guidelines I follow

Kay. Undid all the s_ changes. Private static is s_ again. 

> I still disagree that ILanguageBackend should exist at all.

It's gone. Furthermore, I removed the binary compilation from the LanguageBackend, and put the relevant code into their own binary compilers. This also includes removing the file extension from the LanguageBackend, like you wanted.

*phew* I believe that covers everything now! 😄

Let me know if I'm mistaken, and I've missed something or haven't addressed some point you brought up.

**Comment by mellinoe** [comment]
There's still a few problems, but TBH its just too large and scattered for me to review effectively. Just from a quick scan:

* There is some weird braces going on -- they should just be consistent with the rest of the library. You're putting braces on the ends of lines instead of on their own.
* You've done something with the command line arguments that doesn't seem necessary or helpful to me. It just moves stuff around which was fine before. The exception throwing/catching in Program.cs is kind of unnecessary -- it was doing its job before and now there's too much complexity to follow. I think having the binary compilers similarly overcomplicates ShaderGen.App. Previously, it was super simple and contained in one file. Now there's abstractions and indirections all over the place.

Also, i don't want to remove any of the Debug.Assert's that you've still removed. I understand that the next line is going to null ref or whatever, but the assertions still serve a purpose by signalling the method's intention in a clearer way.

I don't want to be discouraging, but I think you will have to split this up into a series of smaller PR's for me to review it. There's just a bit too much going on. For example, I would definitely look through and merge some PR's that individually did:

* Removed unused usings. Many of the files changed here are just part of this.
* Misc. formatting cleanup (the stuff like removing double semicolons, removing $"" when unnecessary, etc.)
* Splitting the backends into their own namespace / folder
* Test assertion changes

When everything is all jumbled together (and there is undesirable stuff mixed in), it's too hard to review.

**Comment by CloneDeath** [comment]
You have to remember, you're writing code for everyone else, not just yourself.

I strongly suggest picking up a copy of Clean Code by Robert Martin.

> There is some weird braces going on

It's called K&R style. These sort of details are not important. Yes, the code should be uniform, and it is very important that others can decipher what the code is doing. I'm all for removing distractions like this, and it seems like your views on this are contradictory.

* Braces on the same line are a distraction
* s_ is not a distraction

> You've done something with the command line arguments that doesn't seem necessary or helpful to me

The main class was over a hundred lines long. The main function was massive. With these changes, it actually brings some clarity to what's happening.

A function should only do one thing, and do it well. It should be clear that the class takes in the command line arguments, parses them, and cleans them up. Looking at it again, the input validation actually probably belongs in that class too.

> Previously, it was super simple and contained in one file. Now there's abstractions and indirections all over the place.

This seems pretty contradictory to me. You agree that fewer is better and adds clarity. Now, it's broken down into fewer lines, but this is more complex? 

See this from the perspective of others: 

Before, the single file did a dozen different things, it was difficult to list everything that it did, and impossible to tell the scope of any action, variable, or even conceptual goal of sections of the code.

After, things do as they say, variable and their scopes are contained and categorized, and functionality is isolated into their own classes.

> Debug.Assert

It's a distraction. It doesn't add any clarity at all. I understood your `((A && B) || (!A && !B))` logic at a glance. No one would dispute that.

But adding an additional `(A || B)` assertion in the negative case is just a distraction, and made me do a double take. It is literally equivalent to `Debug.Assert(true)`

As for the nullref assertions, all that does is say "And if a value is null here, then a null reference exception will be thrown". But this is true for pretty much every line of code. Not only is this defensive programming, it is a redundant statement that truly is just a distraction.

> too hard to review

How are you diffing? github's file differences view lays it out pretty simply, and even lets you comment on individual lines of code.

**Comment by mellinoe** [comment]
Sorry, I've already spent a bit too much of my time on this, so I'm just going to step away. Again, I'll accept some smaller, focused improvements that I can effectively discuss and look over.

**Pull request closed without merging**
