### PR TITLE
Add Texture2DArrayResource, and implement for all backends

### PR DESCRIPTION
**Pull request by tgjones**

### CODE REVIEW

**Comment by mellinoe** [comment]
Overall it looks good, but I haven't tested HLSL compilation yet. It seems correct from a glance.

The Metal version needs a slight change, because they have actually separated out the array layer into a separate `uint` parameter rather than bundling it in with the XY coordinate.

This patch fixes it: https://github.com/mellinoe/ShaderGen/commit/0afc33cbed443e4303bdb661143cbaefe766521d

**Comment by mellinoe** [comment]
Does it make more sense to expose our builtin function in a similar way to Metal? Conceptually, `float2` + `uint` parameters makes more sense (at least to me) than a single `float3`, since the third component is the array layer, which is not truly a floating-point value. Also, I think it may be more common to store the array layer in a separate location than the 2D texture coordinate for a model (e.g. in a uniform rather than a per-vertex attribute). 

 It's different from how both GLSL and HLSL express it, though. That could be a mark against it.

Thoughts?

**Comment by tgjones** [comment]
I like that idea. It's what I did for #27, and I would have done it here too, if I had realised Metal worked like that.

**Comment by tgjones** [comment]
(If we do this, I guess we should also update the `TextureCubeResource` version of `Sample`, but that can be done separately?)

**Comment by mellinoe** [comment]
TextureCubes are logically sampled with a 3D direction vector, so I don't think we need to change anything there. If we had a TextureCubeArrayResource, then we could use a `uint arrayLayer` parameter for it.

> Shall I make that change?

Yeah, I think we should go ahead and change the signature to:

```C#
public static Vector4 Sample(Texture2DArrayResource texture, SamplerResource sampler, Vector2 texCoords, uint arrayLayer)
```

**Comment by tgjones** [comment]
> TextureCubes are logically sampled with a 3D direction vector

Oops, my brain is not firing on all cylinders today.

> Yeah, I think we should go ahead and change the signature

Done.

**Comment by mellinoe** [comment]
GLES is failing because we need a "default precision specifier" at the top of the file:

https://github.com/mellinoe/ShaderGen/commit/3a27c5d0ecc854473e01b3675f2d55519f94c913

By the way, I've pushed [a new commit to the master branch](https://github.com/mellinoe/ShaderGen/commit/856e36b94ec954b6f3ac4b8ba32400b551b19805) that should let the GL/GLES tests use any `glslangvalidator` tool if it is available on the current path. The tests actually won't check that the generated code actually compiles unless they are able to locate `glslangvalidator`.

**Comment by tgjones** [comment]
Ah, good find.

I'll set `glslangvalidator` up - it's long past time that I stopped using you as my continuous integration test suite for GLSL / Metal ;)

**Comment by mellinoe** [comment]
No problem 😄. I'm happy to run the tests myself in the meantime, especially since I've failed to set up AppVeyor CI tests for this long...

You can download binaries for glslangvalidator from their [GitHub release page](https://github.com/KhronosGroup/glslang/releases). I think I can get AppVeyor to download this as well, but I need to set aside some time to experiment with it. I've been using the `glslangvalidator` tool that comes bundled with the Vulkan SDK, but I think that one is actually a lot older than what is on GitHub.

**Comment by tgjones** [comment]
I've cherry-picked 3a27c5d. Hopefully that will get the tests passing.

**Pull request merged**
