### PR TITLE
Add support for accessing vector using array index

### PR DESCRIPTION
**Pull request by tgjones**
Unfortunately C# doesn't have extension indexers ([yet](https://github.com/dotnet/roslyn/issues/11159)), so this is the best I could come up with.

### CODE REVIEW

**Comment by tgjones** [comment]
I like the idea of exposing the setter. Using `ref float` seems a bit complex though, in both usage and implementation, so I renamed `Item` to `GetComponent`, and added a `SetComponent`. What do you think?

In the future, if extension indexers get added to C#, we can also add that.

**Comment by mellinoe** [comment]
> Using ref float seems a bit complex though, in both usage and implementation

The usage will be a bit awkward, but it didn't actually need any implementation change, from my brief testing. I just changed the return value from `float` to `ref float` and it worked as expected (at least, the code compiled 😄). I was able to write stuff like:

```C#
Vector3 v3 = new Vector3();
v3.Item(0) = v3.Item(1);
v3.Item(2) = 1f;
// etc.
```

I'm fine with doing `GetComponent/SetComponent` as well. It's less "weird" and easier to understand overall.

**Comment by tgjones** [comment]
I learnt something - I didn't realise `ref` returns could be used as l-values like that! Makes sense, of course. I think I've just only seen examples where the variable assignment and setting of the referenced value are on separate lines.

In any case, I think I still prefer `GetComponent` / `SetComponent`.

**Comment by mellinoe** [comment]
> In any case, I think I still prefer GetComponent / SetComponent.

Me too. I'll merge this as it looks good as-is.

**Pull request merged**
